version: '3.8'
services:
  db-admin:
    container_name: db_admin
    build: ./docker-services/postgress-admin
    volumes:
      - admin:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_PASS}
      POSTGRES_DB: ${ADMIN_DBNAME}
    ports:
      - ${ADMIN_PORT}:5432
  language-py:
    container_name: language_py
    build: ./docker-services/python-practice
  language-pg:
    container_name: language_pg
    build: ./docker-services/postgress-practice
    volumes:
      - ./docker-services/postgress-practice/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_USER: ${PRACTICE_USER}
      POSTGRES_DB: ${PRACTICE_DBNAME}
      POSTGRES_PASSWORD: ${PRACTICE_PASS}
    ports:
      - ${PRACTICE_PORT}:5432
  python-server:
    depends_on:
      - db-admin
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    environment:
      ADMIN_HOST: ${ADMIN_HOST}
      ADMIN_PORT: 5432
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      ADMIN_DBNAME: ${ADMIN_DBNAME}
      PRACTICE_HOST: ${PRACTICE_HOST}
      PRACTICE_PORT: 5432
      PRACTICE_USER: ${PRACTICE_USER}
      PRACTICE_PASS: ${PRACTICE_PASS}
      PRACTICE_DBNAME: ${PRACTICE_DBNAME}
      ADMIN_DASHBOARD_PASS: ${ADMIN_DASHBOARD_PASS}
      DOCKER_KILL_TIMEOUT_SECONDS: ${DOCKER_KILL_TIMEOUT_SECONDS}
      APP_SECRET_KEY: ${APP_SECRET_KEY}
      FLASK_ENV: ${RUNNING_MODE}
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:80"

volumes:
  admin:
  practice:
