version: '3.8'
services:
  db-admin:
    container_name: db_admin
    build: ./docker-services/postgress-admin
    volumes:
      - admin:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${ADMIN_USER}
      POSTGRES_PASSWORD: ${ADMIN_PASS}
      POSTGRES_DB: ${ADMIN_DBNAME}
    ports:
      - ${ADMIN_PORT}:5432
  language-pg:
    build: ./docker-services/postgress-practice
    volumes:
      - practice:/var/lib/postgresql/data
      - ./docker-services/postgress-practice/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_USER: ${PRACTICE_USER}
      POSTGRES_DB: ${PRACTICE_DBNAME}
      POSTGRES_PASSWORD: ${PRACTICE_PASS}
    ports:
      - ${PRACTICE_PORT}:5432
    command: ["echo", "CONTAINER IS STOPPED AS IT WILL BE STARTED BY ADMIN"]
  python-server:
    depends_on:
      - db-admin
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    environment:
      ADMIN_DBNAME: ${ADMIN_DBNAME}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASS: ${ADMIN_PASS}
      ADMIN_PORT: ${ADMIN_PORT}
      PRACTICE_DBNAME: ${PRACTICE_DBNAME}
      PRACTICE_USER: ${ADMIN_USER}
      PRACTICE_PASS: ${ADMIN_PASS}
      PRACTICE_PORT: ${ADMIN_PORT}
      ADMIN_DASHBOARD_PASS: ${ADMIN_DASHBOARD_PASS}
      DOCKER_KILL_TIMEOUT_SECONDS: ${DOCKER_KILL_TIMEOUT_SECONDS}
      FLASK_ENV: ${RUNNING_MODE}
    volumes:
      - ./app:/app
    ports:
      - "5000:80"

volumes:
  admin:
  practice:
